//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanMaster
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BarcodeScanEntities : DbContext
    {
        public BarcodeScanEntities()
            : base("name=BarcodeScanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BarcodeMaster> BarcodeMasters { get; set; }
        public virtual DbSet<EngMaster> EngMasters { get; set; }
        public virtual DbSet<ModelMaster> ModelMasters { get; set; }
        public virtual DbSet<Report_Master> Report_Master { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ModelMaster2> ModelMaster2 { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
    
        public virtual ObjectResult<getreportssp_Result> getreportssp(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getreportssp_Result>("getreportssp", startParameter, endParameter);
        }
    
        public virtual int Getfuctionreport(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Getfuctionreport", startParameter, endParameter);
        }
    }
}
