//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngMaster
    {
        public int ID { get; set; }
        public string ModelName { get; set; }
        public string ModelCode { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> UpdatesDateTime { get; set; }
        public string UpdateNo { get; set; }
        public Nullable<bool> Activestatus { get; set; }
        public string Barcode { get; set; }
    }
}
