//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelMaster2
    {
        public int ID { get; set; }
        public string ModelName { get; set; }
        public string ModelCode { get; set; }
        public string PartName { get; set; }
        public string PartType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Activestatus { get; set; }
        public string PartDescription { get; set; }
        public string Barcode { get; set; }
        public string PartNo { get; set; }
        public string ImagePath { get; set; }
    }
}
