//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Master
    {
        public int ID { get; set; }
        public string Barcode { get; set; }
        public string PartName { get; set; }
        public string IDENTIFICATION_MARK { get; set; }
        public bool Check_Status { get; set; }
        public System.DateTime Added_DateTime { get; set; }
    }
}
