//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanMaster
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Report
    {
        public int ID { get; set; }
        public string ModelCode { get; set; }
        public string PartName { get; set; }
        public System.DateTime CreatedDate { get; set; }

        [DisplayName("Status")]
        public Nullable<bool> Activestatus { get; set; }
        public string TStamp { get; set; }
    }
    
}
